### ISSUE TITLE
Attributed Vertices and Edges in NetworkX

### ISSUE THREAD

**Issue by ashvardanian** [unum-cloud/ustore#234]
Our current implementation of NetworkX-like Python bindings constrain graphs to be directed, unlabeled, and not weighted. To support broader functionality, under the same Python interface, three `ukv_collection_t` can live, storing:

1. inverted indexes of relations for each vertex ID.
2. document collection storing metadata for each vertex ID.
3. document collection storing metadata for each edge ID.

The first exists, and the second and third should be added.

**Comment by davvard** [comment]
4aabe9adaab5e5c14a903cde583b95a9ed72919a
e2942935becc980ad28448ed8ee9af870f9d71c7

**Comment by davvard** [comment]
414787e50914f92f2eeb1152c39de70afc743540

**Comment by davvard** [comment]
7fa7c142a3faf16528220657048774e0d7d39018

**Comment by davvard** [comment]
Already implemented NetworkX compatible functions

1. Iterating over whole graph nodes and edges with attributes
2. Iterating over whole graph nodes and edge with custom field attribute and with default value
3. Counting single node, container, or all nodes degrees with and without weights

Upcoming updates

1. Iterating over edges with given nodes
2. getting and setting nodes and edges attributes
