### ISSUE TITLE
Data-loaders for PyTorch and TensorFlow

### ISSUE THREAD

**Issue by ashvardanian** [unum-cloud/ustore#235]
With improved sampling support, Python data loaders can be implemented natively with PyBind11. It may make them faster than in Python but may significantly complicate compilation if media decoding libraries were to be added.

So we can implement the slicing and media resizing logic in Python and put it into the same `ukv` package. It may be implemented like this:

```python
class PyTorchImageLoader:
    def __init__(self, collection, batch_size, mime_type):
        pass
    def __getitem__(self, batch_idx: int):
        bins = collection.sample(batch_size)
        imgs = [PIL.Image.fromarray(x) for x in bins]
        tensors = ...
        return tensors
    def __len__(self):
        return len(collection) / batch_size
```

**Comment by jalajk24** [comment]
Hey @ashvardanian Can you assign me this project? I would like to contribute in this project.

**Comment by ashvardanian** [comment]
Hey! We would be happy to give this task to you. Fo you already have a draft of a solution or a plan for the implementation?

**Comment by kimihailv** [comment]
@ashvardanian Your example isn't consistent with torch data loading logic. DB collection shouldn't do sampling under the hood. User should have an ability to control sampling strategy. For instance, it is crucial in case of multi-gpu training where it is necessary to shard a dataset.
