### ISSUE TITLE
Bug: Python tests don't work without the 'tmp' folder

### ISSUE THREAD

**Issue by DarvinHarutyunyan** [unum-cloud/ustore#283]
### Describe the bug

Python tests don't work without the 'tmp' folder

### Steps to reproduce

Run python tests without the existing 'tmp' folder

### Expected behavior

Working python tests without a pre-existing 'tmp' folder

### UKV version

v0.4.X

### Operating System

Any

### Hardware architecture

x86

### Are you using an embedded version?

- [ ] I use the embedded version

### Which interface are you using?

Official Python bindings

### Which engine are you using?

UMem

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by davvard** [comment]
https://github.com/unum-cloud/ustore/pull/285
