### ISSUE TITLE
Feature: add support for batch import of attributes for `add_edges_from`  in ukv.graph

### ISSUE THREAD

**Issue by AleksandrKent** [unum-cloud/ustore#305]
### Describe what you are looking for

Currently there is ability to add edges in batches with `add_edges_from()` where source node and target node can be supplied as arrays. But attributes are copied fully for all edges. And if I want to provide different edge attributes, I can't do it in batches.

This looks like somewhat in-between NetworkX [add_edges_from](https://networkx.org/documentation/stable/reference/classes/generated/networkx.Graph.add_edges_from.html) and ML-oriented frameworks DGL [add_edges](https://docs.dgl.ai/generated/dgl.DGLGraph.add_edges.html).

Could you add interface where source nodes, target nodes and attributes are all arrays of same size? So i-th row of the each array corresponds to the i-th edge.

### Can you contribute to the implementation?

- [ ] I can contribute

### Is your feature request specific to a certain interface?

It applies to everything

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
A potentially better design might be to allow `merge` operations on the Graph if a person supplies a PyArrow table and specifies which columns should be treated as the source and target ID, automatically routing the remaining ones into edge properties. Thoughts?

**Comment by davvard** [comment]
Yes it is good idea. I think we should have add_edges_from PyArrow table
