### ISSUE TITLE
Feature: MacOS and Clang-compatible builds

### ISSUE THREAD

**Issue by ashvardanian** [unum-cloud/ustore#307]
### Describe what you are looking for

Not every backend of ours supports MacOS, but RocksDB, LevelDB, and UMem likely do. The `CMakeLists.txt` and the `pyproject.toml` must be adjusted to produce MacOS builds.

This may also fix the issues we currently face with Rust bindings in [#238](https://github.com/unum-cloud/ukv/issues/238). This issue also continues #248.

### Can you contribute to the implementation?

- [ ] I can contribute

### Is your feature request specific to a certain interface?

It applies to everything

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DarvinHarutyunyan** [comment]
bd05cad17149021fb3a486ed3be5a5fe95595020
