### ISSUE TITLE
Feature: Add GitHub actions to build and test pull requests

### ISSUE THREAD

**Issue by DarvinHarutyunyan** [unum-cloud/ustore#310]
### Describe what you are looking for

Add GitHub actions to build and test UKV pull requests

### Can you contribute to the implementation?

- [ ] I can contribute

### Is your feature request specific to a certain interface?

It applies to everything

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
We have had similar actions, and they are preserved in history, but we intentionally deprecated them, as they take hours to build and run.
