### ISSUE TITLE
Fix: Stop the server on termination signal

### ISSUE THREAD

**Issue by DarvinHarutyunyan** [unum-cloud/ustore#343]
### Describe what you are looking for

Correct closing of the UStore Server on the termination signal

### Can you contribute to the implementation?

- [ ] I can contribute

### Is your feature request specific to a certain interface?

It applies to everything

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
What does it mean? What's incorrect about the current closing behavior?

**Comment by DarvinHarutyunyan** [comment]
It just doesn't exist
