### ISSUE TITLE
Feature: Create a Server Command Line tool

### ISSUE THREAD

**Issue by DarvinHarutyunyan** [unum-cloud/ustore#345]
### Describe what you are looking for

Create a Server Command Line tool. Description:

```
SYNOPSIS
        ustore --url <URL> [collection (((create | drop) --name <collection name>) | list)] [-h]
        ustore --url <URL> [collection (import --input <input> --id <id field>) | (export --output <output>) 
                            --mlimit <memory limit> [--name <collection name>]] [-h]
        ustore --url <URL> [snapshot (create | (export <path>) | (drop <snapshot id>) | list)] [-h]

OPTIONS
        --url <URL>
                    DB Server URL (remote or local)
        --input <input>
                    Input file path
        --output <output>
                    Output file path
        --id <id field>
                    The field which data will use as key(s)
        --mlimit <memory limit>
                    Size of available RAM for a specific operation in bytes
        -h, --help 
        	    Print this help information on this tool and exit
```

### Can you contribute to the implementation?

- [x] I can contribute

### Is your feature request specific to a certain interface?

It applies to everything

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
Please list the intended command specifications.

**Comment by DarvinHarutyunyan** [comment]
For the first version of the command line tool, we will have a minimal list of commands with which you can connect to the DB Server and work with the main objects like collections and snapshots. In the future we will make amendments and expand the functionality and now I will add a description for the commands above.

**Comment by ashvardanian** [comment]
That’s understandable. Still, we need a list.

**Comment by davvard** [comment]
b85e40fa719b7b6067d1ace40711321ad09a2886
