### ISSUE TITLE
Bug: OpenSSL build failed

### ISSUE THREAD

**Issue by DarvinHarutyunyan** [unum-cloud/ustore#347]
### Describe the bug

OpenSSL build failed

### Steps to reproduce

Build

### Expected behavior

Build

### UStore version

v0.7x

### Operating System

Any

### Hardware architecture

x86

### Are you using an embedded version?

- [ ] I use the embedded version

### Which interface are you using?

Native C interface

### Which engine are you using?

UCSet

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by davvard** [comment]
7824bf6926ea7b57594fdb56519bfd93d356ac74
