### ISSUE TITLE
Feature: Rust wrapper for ustore

### ISSUE THREAD

**Issue by ghost** [unum-cloud/UStore#436]
### Describe what you are looking for

Hi I would love to implement the rust lib wrapper for ustore, and I need some pointers or examples to do it. Thanks 

### Can you contribute to the implementation?

- [X] I can contribute

### Is your feature request specific to a certain interface?

Other

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
There is an ongoing effort for the [UStore Rust bindings over here](https://github.com/unum-cloud/ustore/tree/238-rust-bindings/rust) with a [PR draft over here](https://github.com/unum-cloud/ustore/pull/258). Long term, I think we should deprecate the GoLang frontend and LevelDB backend, potentially open-source our fast storage engine, and prioritize the Rust frontend. Lets continue the discussion in the PR draft, @0xqd 🤗

**Comment by ghost** [comment]
@ashvardanian I see, I will check that PR
